### ISSUE TITLE
Fix security alerts reported by github

### ISSUE THREAD

**Issue by zaibon** [threefoldfoundation/rivine-wallet#19]
Github has identify a couple of security issue: https://github.com/threefoldfoundation/rivine-wallet/network/alerts

**Comment by lucasvanhalst** [comment]
None of them are important / applicable, those are dependencies used by the build tools so none of them are actually shipped

**Comment by zaibon** [comment]
Can you dismiss them somehow ? so I don't get spammed about them ?
